version: "3.9"

# For use in development only.

services:

  redis:
    container_name: poster_redis
    deploy:
      resources:
        limits:
          # When set to 0 these will use as much as needed:
          cpus: "0"
          memory: "0"
    image: "redis:7-bullseye"
    ports:
      - "6666:6379"
    restart: unless-stopped
    stop_grace_period: "3s"
    volumes:
      - "redis:/data"

volumes:
  redis:
